### ISSUE TITLE
Sorting of lists on various pages

### ISSUE THREAD

**Issue by marksherman** [NatTuck/bottlenose-classic#38]
Your Courses : "/courses" : Someday we may need more organization here, possibly sorting by (some) date. Fine for now, as there's only one semester at a time. 

Course page : "/courses/#" : Students are listed in no discernable order. Sorting here may aid teachers/graders matching to registrar or other system lists.

Student Status Report : "/registrations/##" : Assignment list appears to be in chronological order, newest last. Sort assignments with newest at top.

Submissions by $student for $assignment : "/registrations/##/submissions_for_assignment/###" : Assignments should be ordered by date, ideally newest at top.

Assignment Description : "/assignments/###" : students appear to be sorted alphabetically. Confirm as intentional.

**Comment by NatTuck** [comment]
/courses - Courses are ordered alphabetically. I'm going to ignore the multiple-semesters problem for now.
/courses/# - Students are listed in alphabetical order.
/registrations/# - Assignments are listed in alphabetical order on (chapter name, assignment name). Reverse order only really makes sense if assignments are never posted early.
/registrations/#/submissions_for_assignment/# - Ordered by date, newest at top.
/assignments/# - Students are listed alphabetically

I like order by name since it gives more control and consistency than order by date (which date? what if a due date is bumped back?). Let me know if there's some reason not to do it that way.
