### ISSUE TITLE
email addresses seem to be treated as case-sensitive

### ISSUE THREAD

**Issue by derrell** [NatTuck/bottlenose-classic#5]
When a student enters an email address to have a new link sent, it seems that the case of the email address must be exactly what was originally entered in the registration of the user. Although technically email addresses are case sensitive, in practice, they are treated as case insensitive and capitalized almost randomly at different times. They should be treated as case insensitive here.

**Comment by marksherman** [comment]
The student who discovered the bug entered an email with mixed cases into bottlenose. So in the database, and all views, it appears as aBBa.
The student received the email link, but the link did not work, saying email "abba" was unknown.
I changed the database to be "abba" instead of "aBBa" and the student's link then worked.

That should help narrow it down.

**Comment by NatTuck** [comment]
Fix pushed. Email addresses are now downcased before save by the user model. Run the script "script/cleanup-db" to find and fix any other mixed-case email addresses.
